---
schemaVersion: '2.2'
description: see if kernel has been updated and a reboot is necessary
parameters: {}
mainSteps:
- action: aws:runShellScript
  name: InstallAppSupportAppsBashScript
  inputs:
    runCommand:
    - 'needs-restarting -r ; echo $?'
